<a href="https://colab.research.google.com/github/AdityaTheDev/Pytorch-learnings/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# simple single neuron neural network

In [7]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out


In [8]:
# dataset
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)


tensor([[0.5505],
        [0.5631],
        [0.5360],
        [0.5973],
        [0.5727],
        [0.5724],
        [0.5932],
        [0.5617],
        [0.5715],
        [0.5685]], grad_fn=<SigmoidBackward0>)

In [14]:
!pip install torchinfo

In [16]:
import torchinfo
from torchinfo import summary
summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
model.linear.weight
model.linear.bias

Parameter containing:
tensor([0.2968], requires_grad=True)

# Neural network with 5 inputs, 3 neurons and 1 output - sigmoid

In [21]:
import torch
import torch.nn as nn

class ThreeNeuron(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out


In [24]:
# dataset
features=torch.rand(10,5)
model=ThreeNeuron(features.shape[1])
model(features)

tensor([[0.5536],
        [0.5423],
        [0.5424],
        [0.5642],
        [0.5365],
        [0.5694],
        [0.5746],
        [0.5123],
        [0.5436],
        [0.5520]], grad_fn=<SigmoidBackward0>)

In [26]:
model.linear2.weight

Parameter containing:
tensor([[0.5187, 0.4506, 0.3371]], requires_grad=True)

In [27]:
summary(model,features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
ThreeNeuron                              [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# using Sequential() container

In [32]:
import torch
import torch.nn as nn

class UsingSequentialContainer(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out=self.network(features)
    return out

In [28]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [33]:
# create dataset
features = torch.rand(10,5)

# create model
model = UsingSequentialContainer(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6722],
        [0.7078],
        [0.6623],
        [0.6735],
        [0.6870],
        [0.6997],
        [0.6690],
        [0.6610],
        [0.6716],
        [0.7021]], grad_fn=<SigmoidBackward0>)

In [45]:
summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
UsingSequentialContainer                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [48]:
model.network[0].weight
model.network[2].weight

Parameter containing:
tensor([[0.3562, 0.1783, 0.5504]], requires_grad=True)