<a href="https://colab.research.google.com/github/AdityaTheDev/Pytorch-learnings/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.4894, 0.2558, 0.3193],
        [0.9317, 0.4503, 0.3181]])

In [11]:
# use of seed
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,5))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [25]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
x.shape

torch.Size([2, 3])

In [29]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068655667629010229, 3688512082115442480, 6500727496461464878]])

In [30]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [38]:
x.dtype

torch.int64

In [39]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.2215, 0.3271, 0.1352],
        [0.6283, 0.3030, 0.1302]], dtype=torch.float64)

## Tensor Data Types

In [40]:
# find data type
x.dtype

torch.int64

In [41]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [42]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [45]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [46]:
y=x.to(torch.float32)
y.dtype

torch.float32

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [47]:
x = torch.rand(2,2)
x

tensor([[0.6476, 0.3430],
        [0.3182, 0.5261]])

In [48]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.4194, 0.1177],
        [0.1013, 0.2768]])

### 2. Element wise operation

In [49]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])
tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])


In [50]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0447, 0.1735, 0.2839],
        [0.0458, 0.4450, 0.3591]])

In [51]:
c = torch.tensor([1, -2, 3, -4])

In [52]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [53]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [54]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [55]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [56]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [57]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [58]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [60]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 8., 8.],
        [3., 3., 5.]])

In [63]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([19., 11.])

In [64]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.0000, 5.5000, 6.5000])

In [65]:
# median
torch.median(e)

tensor(3.)

In [66]:
# max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [67]:
# product
torch.prod(e)

tensor(8640.)

In [68]:
# standard deviation
torch.std(e)

tensor(2.4495)

In [69]:
# variance
torch.var(e)

tensor(6.)

In [70]:
# argmax
torch.argmax(e)

tensor(1)

In [71]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [72]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2],
        [3, 8],
        [5, 6]])


In [73]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[38, 72],
        [44, 88]])

In [74]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [75]:
# transpose
torch.transpose(f, 0, 1)

tensor([[0, 0],
        [6, 8],
        [4, 4]])

In [77]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 4., 4.],
        [1., 1., 2.],
        [4., 7., 2.]])

In [78]:
# determinant
torch.det(h)

tensor(-24.)

In [79]:
# inverse
torch.inverse(h)

tensor([[ 0.5000, -0.8333, -0.1667],
        [-0.2500,  0.2500,  0.2500],
        [-0.1250,  0.7917, -0.0417]])

### 5. Comparison operations

In [80]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 6, 1],
        [4, 5, 6]])
tensor([[9, 2, 3],
        [1, 0, 2]])


In [81]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [82]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 2., 7.],
        [9., 2., 4.]])

In [83]:
# log
torch.log(k)

tensor([[0.0000, 0.6931, 1.9459],
        [2.1972, 0.6931, 1.3863]])

In [84]:
# exp
torch.exp(k)

tensor([[2.7183e+00, 7.3891e+00, 1.0966e+03],
        [8.1031e+03, 7.3891e+00, 5.4598e+01]])

In [85]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 1.4142, 2.6458],
        [3.0000, 1.4142, 2.0000]])

In [86]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.8808, 0.9991],
        [0.9999, 0.8808, 0.9820]])

In [87]:
# softmax
torch.softmax(k, dim=0)

tensor([[3.3535e-04, 5.0000e-01, 9.5257e-01],
        [9.9966e-01, 5.0000e-01, 4.7426e-02]])

In [88]:
# relu
torch.relu(k)

tensor([[1., 2., 7.],
        [9., 2., 4.]])

## Inplace Operations

In [89]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])
tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])


In [90]:
m.add_(n)

tensor([[0.6556, 0.4835, 0.8263],
        [1.5441, 0.8216, 1.5681]])

In [91]:
m

tensor([[0.6556, 0.4835, 0.8263],
        [1.5441, 0.8216, 1.5681]])

In [92]:
n

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [93]:
torch.relu(m)

tensor([[0.6556, 0.4835, 0.8263],
        [1.5441, 0.8216, 1.5681]])

In [94]:
m.relu_()

tensor([[0.6556, 0.4835, 0.8263],
        [1.5441, 0.8216, 1.5681]])

In [95]:
m

tensor([[0.6556, 0.4835, 0.8263],
        [1.5441, 0.8216, 1.5681]])

## Copying a Tensor

In [96]:
a = torch.rand(2,3)
a

tensor([[0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [97]:
b = a

In [98]:
b

tensor([[0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [99]:
a[0][0] = 0

In [100]:
a

tensor([[0.0000, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [101]:
b

tensor([[0.0000, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [102]:
id(a)

137813893518576

In [103]:
id(b)

137813893518576

In [104]:
b = a.clone()

In [105]:
a

tensor([[0.0000, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [106]:
b

tensor([[0.0000, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [107]:
a[0][0] = 10

In [108]:
a

tensor([[10.0000,  0.3397,  0.1879],
        [ 0.5534,  0.2682,  0.9556]])

In [109]:
b

tensor([[0.0000, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])

In [110]:
id(a)

137813893518576

In [111]:
id(b)

137813893518672